config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :courses
  # get 'welcome/index'
  root 'welcome#index'
  resources :students
  resources :demos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :description, presence: true
  has_and_belongs_to_many :students
end

app/models/demo.rb
class Demo < ApplicationRecord

  validates :name,  presence: true
  validates :title, acceptance: {accept: ['TRUE', 'accepted']}

  before_validation :ensure_name_has_value

  private
    def ensure_name_has_value
      if name.blank?
        self.name = title
      end
    end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :student_projects
  has_many :students, through: :student_projects
end

app/models/student.rb
class Student < ApplicationRecord
   has_many :blogs
   has_and_belongs_to_many :courses
   has_many :student_projects


   has_many :projects, through: :student_projects
   validate :contact_information, on: :contact_info
   validate :personal_information, on: :personal_info
   validates :first_name, format: { with: /\A[a-zA-Z]+\z/, message: "Only letters allows"}
   # validates :first_name, :last_name, :email, presence: true
   # validates :email, confirmation: true
   validates :email_confirmation, presence: true, if: :email_changed?
   after_create :display_student_age




   def display_student_age
      if self.date_of_birth.present?
         age = Date.today.year - self.date_of_birth.year
         puts "=========Age of Student is #{age}========="
      else
         puts "======Age can not be calculated without date_oh_birth========"
      end
   end



   # before_create :display_greetings

   # def display_greetings
   #    puts 'Hello, you executed before action callback!'   
   # end
  

   def contact_information
      errors.add(:base, "Email must be present") if email.blank?
      errors.add(:base, "Phone number must be present") if contact.blank?
   end

   def personal_information
      errors.add(:base, "First Name must be present") if first_name.blank?
      error.add(:base, "Last Name must be present") if last_name.blank?
   end



end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_path, status: :see_other, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :description)
    end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: %i[show edit update destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    #   first_name: params[:student][:first_name],
    #   last_name: params[:student][:last_name],
    #   email: params[:student][:email]
    # )
    if @student.save
      redirect_to students_path, notice: 'Student has been created sucessfully'
    else
       render :new, status: :unprocessable_entity
    end
  end


  #This will show the details of student


  def show
    # @student = Student.find(params[:id])
  end

  # This will edit the deatils of student

  def edit
    # @student = Student.find(params[:id])
  end

  #This will update the details of student

  def update
    # @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to student_path(@student),notice: 'Student has been updated sucessfully'

    else
      render :edit, status: :unprocessable_entity
    end
  end

  #This will delete the data of student

  def destroy
    # @student = Student.find(params[:id])
    @student.destroy
    redirect_to student_path, notice: 'Student has been deleted sucessfully'
  end


  private 

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :email_confirmation, :date_of_birth, :contact, :address)
  end

  def set_student
    @student = Student.find(params[:id])
    
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= course.description %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<% content_for :title, "Editing course" %>

<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Courses" %>

<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", course %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/new.html.erb
<% content_for :title, "New course" %>

<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/demos/_form.html.erb
<%= form_with model: demo do |form| %>


<div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
</div>

<div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
</div>

<div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
</div>

<div>
    <%= form.submit %>
</div>

<% end %>

app/views/demos/index.html.erb
<h1>HEllo World</h1>

app/views/demos/new.html.erb
<h1> New demo</h1>


<%= render partial: "form", locals: { demo: @demo }  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Student Mgmt" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>

<% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message|%>
    <p><%= message %></p>
    <% end %>
<% end %>

<div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
</div>

<div>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
</div>

<div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
</div>

<div>
    <%= form.label :email_confirmation %><br>
    <%= form.email_field :email_confirmation %>
</div>

<div>
    <%= form.label :date_of_birth %><br>
    <%= form.date_field :date_of_birth %>
</div>

<div>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
</div>

<div>
    <%= form.label :contact %><br>
    <%= form.number_field :contact %>
</div>

<div>
    <%= form.submit %>
</div>

<% end %>

app/views/students/edit.html.erb
<h1> Edit Student</h1>

<%= render "form", student: @student %>

app/views/students/index.html.erb
<p><%= notice %></p>

<h1>Listing Students</h1>
<%= link_to 'New Student', new_student_path %>

<table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Date Of Birth</th>
            <th>Address</th>
            <th>Contact</th>

            <th colspan= "3"> Actions </th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %>  
            <tr>
                <td><%= student.first_name %></td>
            
                <td><%= student.last_name %></td>
                <td><%= student.email %></td>
                 <td><%= student.date_of_birth %>
                <td><%= student.address %>
                <td><%= student.contact %>

                <td><%= link_to 'View', student %></td>
                <td><%= link_to 'Edit', edit_student_path(student) %></td>
                <td><%= link_to 'Delete', student, data: {turbo_method: :delete, turbo_confirm: "Are You Sure?"} %></td> 
               
            </tr>
        <% end %>    
    </tbody>
</table>

app/views/students/new.html.erb
<h1> New Student</h1>


<%= render partial: "form", locals: { student: @student }  %>

app/views/students/show.html.erb
<p><%= notice %></p>
<h1>Student Details</h1>

<p><strong>First Name: </strong><%= @student.first_name %></p>
<p><strong>Last Name: </strong><%= @student.last_name %></p>
<p><strong>Email: </strong><%= @student.email %></p>
<p><strong>Date Of Birth: </strong><%= @student.date_of_birth %></p>
<p><strong>Address: </strong><%= @student.address %></p>
<p><strong>Contact: </strong><%= @student.contact %></p>

<%= link_to 'Back', students_path %> | <%= link_to 'Edit', edit_student_path(@student) %>

app/views/welcome/index.html.erb
<h1>Hello World!!</h1>